### ISSUE TITLE
咨询一下怎么指定一些特定的图片

### ISSUE THREAD

**Issue by 838514984** [lumina37/rotate-captcha-crack#31]
准备数据集
我这里直接扒的[谷歌街景](https://www.crcv.ucf.edu/data/GMCP_Geolocalization/)和[Landscape-Dataset](https://github.com/yuweiming70/Landscape-Dataset)，你也可以自己收集一些风景照并放到一个文件夹里，图像没有尺寸要求

在train.py里配置dataset_root变量指向装有图片的文件夹

不需要手动标注，dataset会在读取图片的同时自动完成矩形裁剪、缩放旋转等工作

我按照上面的要求，放了一些图片在文件夹里面，也在代码里面指定了路径，最后还是运行不起来，咨询下对图片的名称啊啥的有其他要求吗，谢谢大佬。

**Comment by Starry-OvO** [comment]
我这里没说清楚，如果要适配别的数据集，比如假设你的数据集里全是可用的jpg图片，那么把

https://github.com/Starry-OvO/rotate-captcha-crack/blob/master/train_RotNetR.py#L30

改成

```
img_paths = list(dataset_root.glob('*.png'))
```

就行

总得来说，只要输入的`img_paths`是一个图片路径组成的序列就行

**Comment by 838514984** [comment]
> 我这里没说清楚，如果要适配别的数据集，比如假设你的数据集里全是可用的jpg图片，那么把
> 
> https://github.com/Starry-OvO/rotate-captcha-crack/blob/f6df38d5748a71686c052ea299bec7d0593f5d3a/train_RotNetR.py#L30
> 
> 改成
> 
> ```
> img_paths = list(dataset_root.glob('*.png'))
> ```
> 
> 就行
> 
> 总得来说，只要输入的`img_paths`是一个图片路径组成的序列就行

大佬，我是jpg格式，img_paths = list(dataset_root.glob('*.png'))，这里应该改成img_paths = list(dataset_root.glob('*.jpg'))吧~

但是还是报错呢，提示：
  File "C:\Users\admin\rotate-captcha-crack\train_RotNetR.py", line 35, in <module>
    train_dataset = train_img_paths | path_to_tensor | Rotator() | DEFAULT_NORM | labelling | tuple
TypeError: unsupported operand type(s) for |: 'list' and 'function'

能再帮忙看一下嘛，感谢

**Comment by Starry-OvO** [comment]
好久没有我自己都忘了怎么用的了，这个问题应该是我漏了用`SequenceRoot`包装导致不支持管道运算符

开头加一行
```python
from rotate_captcha_crack.dataset.pipeline import SequenceRoot
```

然后把取图片的那一行改成

```python
img_paths = SequenceRoot(list(dataset_root.glob('*.jpg')))
```

应该就可以了

**Comment by 838514984** [comment]
> 好久没有我自己都忘了怎么用的了，这个问题应该是我漏了用`SequenceRoot`包装导致不支持管道运算符
> 
> 开头加一行
> 
> ```python
> from rotate_captcha_crack.dataset.pipeline import SequenceRoot
> ```
> 
> 然后把取图片的那一行改成
> 
> ```python
> img_paths = SequenceRoot(list(dataset_root.glob('*.jpg')))
> ```
> 
> 应该就可以了

大佬，好像droplast不能为true，true的时候报错，false的时候貌似可以跑起来，跑起来之后等他自己运行结束就可以了吗
![报错信息](https://github.com/Starry-OvO/rotate-captcha-crack/assets/20331198/e040f41c-859a-47b2-aae0-4000e4b5547b)

**Comment by Starry-OvO** [comment]
呃这个可能是因为你的图片数量不够用导致全都被drop掉了，改成false也不是不行，但数据量少的话效果可能不会太好

**Comment by 838514984** [comment]
> 呃这个可能是因为你的图片数量不够用导致全都被drop掉了，改成false也不是不行，但数据量少的话效果可能不会太好

效果确实不大好，想请教下大佬，现在验证码的图片是固定的十几张图片然后每次一张随机旋转度数拿来验证，问一下这种情况用什么方法比较好啊，用现有的模型正确率不是很高，有没有好的方法

**Comment by Starry-OvO** [comment]
暴力一点就脱库然后每转5°角计算一个dhash，输入图像算dhash后做向量搜索就可以了

**Comment by 838514984** [comment]
> 暴力一点就脱库然后每转5°角计算一个dhash，输入图像算dhash后做向量搜索就可以了

大佬不好意思，这个我有点不懂，我原本想是能不能把每个图片从0旋转到360像你说的每5度存一张，然后角度标记在文件名上，但是我看代码里面的数据集，标记好像没有跟角度相关的。
数据集处理应该是这里吧，请教一下应该怎么做呢，十分感谢。
![1](https://github.com/Starry-OvO/rotate-captcha-crack/assets/20331198/fedc60f0-f93d-413d-af6e-a9450050097b)

**Comment by Starry-OvO** [comment]
我这个旋转的实现跟管道机制是强耦合的，可能不是太好用哦。如果是暴力枚举的话不如自己写

**Comment by lumina37** [comment]
最新版本已经优化了对自定义数据集的支持，把数据集的图像路径的列表（`list[pathlib.Path]`）赋给`img_paths`就可以了
