### ISSUE TITLE
 执行python .\test_captcha.py报错 

### ISSUE THREAD

**Issue by 17674037041** [lumina37/rotate-captcha-crack#35]
![image](https://github.com/user-attachments/assets/3e0bfb60-b787-40e0-bbf3-b8c359f7530d)

执行python .\test_captcha.py报错    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RotNetR:

**Comment by lumina37** [comment]
最近刚转到UniRepLKNet所以ckpt是对不上的，得用release所在的那个tag的源码才能顺利加载

**Comment by lumina37** [comment]
> 请问这个问题怎么解决啊

稍等等我训个新的ckpt出来，之前的ckpt只能在对应的那个版本用

**Comment by lumina37** [comment]
新ckpt已经训出来了，目测效果会比之前的好不少
